type Payload = {
  payload: {
    policy_dot: Window | null;
    input: Record<string, any>;
  };
};

const dotB2bLoan = open("../digraphs/b2b_loan_policy.dot");
const dotHealthInsurance = open("../digraphs/health_insurance_policy.dot");
const dotMortgageApproval = open("../digraphs/mortgage_approval_policy.dot");
const dotTravelVisa = open("../digraphs/travel_visa_policy.dot");
const dotEmployeeHiring = open("../digraphs/employee_hiring_policy.dot");
const dotMedicalClaims = open("../digraphs/medical_claims_adjudication.dot");

export const mapPayload: Payload[] = [
  // ─────────────────────────────────────────────
  // b2b_loan_policy.dot
  // ─────────────────────────────────────────────
  {
    // reject_bankrupt: has_recent_bankruptcy=true
    payload: {
      policy_dot: dotB2bLoan,
      input: {
        has_recent_bankruptcy: true,
        company_age_years: 0,
        annual_revenue: 0,
        current_debt: 0,
        owner_credit_score: 0,
        industry_risk: "high",
      },
    },
  },
  {
    // approve_e_platinum: established, high revenue, safe DTI, great credit, low risk
    payload: {
      policy_dot: dotB2bLoan,
      input: {
        has_recent_bankruptcy: false,
        company_age_years: 5,
        annual_revenue: 25000000,
        current_debt: 1000000,
        owner_credit_score: 800,
        industry_risk: "low",
      },
    },
  },
  {
    // g_dti_reject: growing company, revenue 1M, debt 600k (DTI=0.6 >= 0.5)
    payload: {
      policy_dot: dotB2bLoan,
      input: {
        has_recent_bankruptcy: false,
        company_age_years: 2,
        annual_revenue: 1000000,
        current_debt: 600000,
        owner_credit_score: 750,
        industry_risk: "low",
      },
    },
  },
  {
    // review_e: established, low revenue, warn DTI, low credit, high risk
    payload: {
      policy_dot: dotB2bLoan,
      input: {
        has_recent_bankruptcy: false,
        company_age_years: 10,
        annual_revenue: 1500000,
        current_debt: 200000,
        owner_credit_score: 650,
        industry_risk: "high",
      },
    },
  },
  {
    // reject_startup: company_age < 1 year
    payload: {
      policy_dot: dotB2bLoan,
      input: {
        has_recent_bankruptcy: false,
        company_age_years: 0.5,
        annual_revenue: 300000,
        current_debt: 0,
        owner_credit_score: 720,
        industry_risk: "medium",
      },
    },
  },
  {
    // approve_g_tier1: growing, high revenue, safe DTI, credit>=700, low risk
    payload: {
      policy_dot: dotB2bLoan,
      input: {
        has_recent_bankruptcy: false,
        company_age_years: 2,
        annual_revenue: 3000000,
        current_debt: 500000,
        owner_credit_score: 730,
        industry_risk: "low",
      },
    },
  },
  {
    // approve_e_gold: established, mid revenue, safe DTI, high credit, medium risk
    payload: {
      policy_dot: dotB2bLoan,
      input: {
        has_recent_bankruptcy: false,
        company_age_years: 7,
        annual_revenue: 3000000,
        current_debt: 600000,
        owner_credit_score: 700,
        industry_risk: "medium",
      },
    },
  },
  {
    // reject_risk: warn DTI, low credit, high risk (growing)
    payload: {
      policy_dot: dotB2bLoan,
      input: {
        has_recent_bankruptcy: false,
        company_age_years: 2,
        annual_revenue: 800000,
        current_debt: 320000,
        owner_credit_score: 680,
        industry_risk: "high",
      },
    },
  },
  {
    // approve_e_silver: established, enterprise revenue, warn DTI, good credit, medium risk
    payload: {
      policy_dot: dotB2bLoan,
      input: {
        has_recent_bankruptcy: false,
        company_age_years: 12,
        annual_revenue: 25000000,
        current_debt: 18000000,
        owner_credit_score: 710,
        industry_risk: "medium",
      },
    },
  },
  // ─────────────────────────────────────────────
  // health_insurance_policy.dot
  // ─────────────────────────────────────────────
  {
    // reject_nonresident: us_resident=false
    payload: {
      policy_dot: dotHealthInsurance,
      input: {
        us_resident: false,
        applicant_age: 35,
        household_income_pct_fpl: 200,
        guardian_present: false,
        parent_has_coverage: false,
        employer_offer: false,
        employer_coverage_pct: 0,
        state_expanded_medicaid: false,
        chronic_conditions: 0,
        bmi: 22,
        tobacco_user: false,
        years_smoking: 0,
        alcohol_units_week: 5,
        exercise_days_week: 3,
        preferred_network: "hmo",
        risk_score: 10,
        terminal_illness: false,
        hospice_care: false,
        enroll_type: "marketplace",
        subsidy_applied: "none",
      },
    },
  },
  {
    // plan_platinum: adult, employer offer 80%+, clean health, low risk, ppo preferred, high income
    payload: {
      policy_dot: dotHealthInsurance,
      input: {
        us_resident: true,
        applicant_age: 38,
        household_income_pct_fpl: 450,
        guardian_present: false,
        parent_has_coverage: false,
        employer_offer: true,
        employer_coverage_pct: 85,
        state_expanded_medicaid: false,
        chronic_conditions: 0,
        bmi: 23,
        tobacco_user: false,
        years_smoking: 0,
        alcohol_units_week: 4,
        exercise_days_week: 5,
        preferred_network: "ppo",
        risk_score: 75,
        terminal_illness: false,
        hospice_care: false,
        enroll_type: "employer",
        subsidy_applied: "none",
      },
    },
  },
  {
    // plan_chip_enroll: minor, income<=200% FPL, guardian present
    payload: {
      policy_dot: dotHealthInsurance,
      input: {
        us_resident: true,
        applicant_age: 8,
        household_income_pct_fpl: 150,
        guardian_present: true,
        parent_has_coverage: false,
        employer_offer: false,
        employer_coverage_pct: 0,
        state_expanded_medicaid: true,
        chronic_conditions: 0,
        bmi: 20,
        tobacco_user: false,
        years_smoking: 0,
        alcohol_units_week: 0,
        exercise_days_week: 5,
        preferred_network: "hmo",
        risk_score: 5,
        terminal_illness: false,
        hospice_care: false,
        enroll_type: "chip",
        subsidy_applied: "full",
      },
    },
  },
  {
    // plan_hsa_hdhp: adult, hdhp preferred, clean health, low risk, no chronic conditions
    payload: {
      policy_dot: dotHealthInsurance,
      input: {
        us_resident: true,
        applicant_age: 32,
        household_income_pct_fpl: 350,
        guardian_present: false,
        parent_has_coverage: false,
        employer_offer: false,
        employer_coverage_pct: 0,
        state_expanded_medicaid: false,
        chronic_conditions: 0,
        bmi: 24,
        tobacco_user: false,
        years_smoking: 0,
        alcohol_units_week: 3,
        exercise_days_week: 4,
        preferred_network: "hdhp",
        risk_score: 20,
        terminal_illness: false,
        hospice_care: false,
        enroll_type: "marketplace",
        subsidy_applied: "partial",
      },
    },
  },
  {
    // reject_risk_too_high: adult, ppo, high risk_score > 90
    payload: {
      policy_dot: dotHealthInsurance,
      input: {
        us_resident: true,
        applicant_age: 55,
        household_income_pct_fpl: 500,
        guardian_present: false,
        parent_has_coverage: false,
        employer_offer: false,
        employer_coverage_pct: 0,
        state_expanded_medicaid: false,
        chronic_conditions: 5,
        bmi: 42,
        tobacco_user: true,
        years_smoking: 20,
        alcohol_units_week: 20,
        exercise_days_week: 0,
        preferred_network: "ppo",
        risk_score: 95,
        terminal_illness: false,
        hospice_care: false,
        enroll_type: "marketplace",
        subsidy_applied: "none",
      },
    },
  },
  {
    // plan_silver: young adult on parent coverage, managed conditions, partial subsidy
    payload: {
      policy_dot: dotHealthInsurance,
      input: {
        us_resident: true,
        applicant_age: 24,
        household_income_pct_fpl: 250,
        guardian_present: false,
        parent_has_coverage: true,
        employer_offer: false,
        employer_coverage_pct: 0,
        state_expanded_medicaid: false,
        chronic_conditions: 1,
        bmi: 27,
        tobacco_user: false,
        years_smoking: 0,
        alcohol_units_week: 8,
        exercise_days_week: 2,
        preferred_network: "hmo",
        risk_score: 42,
        terminal_illness: false,
        hospice_care: false,
        enroll_type: "dependent",
        subsidy_applied: "partial",
      },
    },
  },
  {
    // plan_bronze: full subsidy, hmo, low risk score
    payload: {
      policy_dot: dotHealthInsurance,
      input: {
        us_resident: true,
        applicant_age: 29,
        household_income_pct_fpl: 130,
        guardian_present: false,
        parent_has_coverage: false,
        employer_offer: false,
        employer_coverage_pct: 0,
        state_expanded_medicaid: true,
        chronic_conditions: 0,
        bmi: 21,
        tobacco_user: false,
        years_smoking: 0,
        alcohol_units_week: 2,
        exercise_days_week: 4,
        preferred_network: "hmo",
        risk_score: 15,
        terminal_illness: false,
        hospice_care: false,
        enroll_type: "marketplace",
        subsidy_applied: "full",
      },
    },
  },
  // ─────────────────────────────────────────────
  // mortgage_approval_policy.dot
  // ─────────────────────────────────────────────
  {
    // reject_ineligible_applicant: undocumented citizenship
    payload: {
      policy_dot: dotMortgageApproval,
      input: {
        citizenship_status: "undocumented",
        military_service: false,
        va_entitlement: false,
        property_rural: false,
        household_income_pct_area_median: 100,
        credit_score: 700,
        loan_amount: 300000,
        down_payment_pct: 20,
        employment_type: "w2",
        employment_months: 36,
        gross_annual_income: 90000,
        avg_net_income: 0,
        tax_returns_available: 0,
        retirement_income_documented: false,
        income_source_country: "US",
        forex_risk: "low",
        front_end_dti: 25,
        back_end_dti: 35,
        derogatory_marks: 0,
        collections: 0,
        foreclosure_last_7y: false,
        ltv: 80,
        appraisal_value: 400000,
        purchase_price: 400000,
        property_condition: "good",
        zoning: "residential",
        flood_zone: false,
        no_exception: true,
        cred_profile: "prime",
        ltv_category: "excellent",
      },
    },
  },
  {
    // loan_tier_a: conventional, w2 stable, excellent DTI, prime credit, 20% down, good appraisal
    payload: {
      policy_dot: dotMortgageApproval,
      input: {
        citizenship_status: "citizen",
        military_service: false,
        va_entitlement: false,
        property_rural: false,
        household_income_pct_area_median: 120,
        credit_score: 800,
        loan_amount: 500000,
        down_payment_pct: 25,
        employment_type: "w2",
        employment_months: 48,
        gross_annual_income: 150000,
        avg_net_income: 0,
        tax_returns_available: 0,
        retirement_income_documented: false,
        income_source_country: "US",
        forex_risk: "low",
        front_end_dti: 22,
        back_end_dti: 32,
        derogatory_marks: 0,
        collections: 0,
        foreclosure_last_7y: false,
        ltv: 75,
        appraisal_value: 670000,
        purchase_price: 650000,
        property_condition: "good",
        zoning: "residential",
        flood_zone: false,
        no_exception: true,
        cred_profile: "prime",
        ltv_category: "excellent",
      },
    },
  },
  {
    // loan_tier_e (FHA): fha path, w2 12mo, marginal DTI, subprime, high LTV
    payload: {
      policy_dot: dotMortgageApproval,
      input: {
        citizenship_status: "citizen",
        military_service: false,
        va_entitlement: false,
        property_rural: false,
        household_income_pct_area_median: 80,
        credit_score: 590,
        loan_amount: 280000,
        down_payment_pct: 3.5,
        employment_type: "w2",
        employment_months: 14,
        gross_annual_income: 55000,
        avg_net_income: 0,
        tax_returns_available: 0,
        retirement_income_documented: false,
        income_source_country: "US",
        forex_risk: "low",
        front_end_dti: 34,
        back_end_dti: 48,
        derogatory_marks: 0,
        collections: 0,
        foreclosure_last_7y: false,
        ltv: 96.5,
        appraisal_value: 290000,
        purchase_price: 290000,
        property_condition: "good",
        zoning: "residential",
        flood_zone: false,
        no_exception: true,
        cred_profile: "subprime",
        ltv_category: "high",
      },
    },
  },
  {
    // reject_unverifiable_income: w2 < 24 months on conventional, no exception
    payload: {
      policy_dot: dotMortgageApproval,
      input: {
        citizenship_status: "citizen",
        military_service: false,
        va_entitlement: false,
        property_rural: false,
        household_income_pct_area_median: 110,
        credit_score: 720,
        loan_amount: 400000,
        down_payment_pct: 15,
        employment_type: "w2",
        employment_months: 10,
        gross_annual_income: 100000,
        avg_net_income: 0,
        tax_returns_available: 0,
        retirement_income_documented: false,
        income_source_country: "US",
        forex_risk: "low",
        front_end_dti: 26,
        back_end_dti: 38,
        derogatory_marks: 0,
        collections: 0,
        foreclosure_last_7y: false,
        ltv: 85,
        appraisal_value: 470000,
        purchase_price: 470000,
        property_condition: "good",
        zoning: "residential",
        flood_zone: false,
        no_exception: true,
        cred_profile: "near_prime",
        ltv_category: "standard",
      },
    },
  },
  {
    // prop_reject: flood_zone=true, high LTV
    payload: {
      policy_dot: dotMortgageApproval,
      input: {
        citizenship_status: "citizen",
        military_service: false,
        va_entitlement: false,
        property_rural: false,
        household_income_pct_area_median: 100,
        credit_score: 760,
        loan_amount: 350000,
        down_payment_pct: 10,
        employment_type: "w2",
        employment_months: 36,
        gross_annual_income: 120000,
        avg_net_income: 0,
        tax_returns_available: 0,
        retirement_income_documented: false,
        income_source_country: "US",
        forex_risk: "low",
        front_end_dti: 24,
        back_end_dti: 38,
        derogatory_marks: 0,
        collections: 0,
        foreclosure_last_7y: false,
        ltv: 90,
        appraisal_value: 390000,
        purchase_price: 390000,
        property_condition: "good",
        zoning: "residential",
        flood_zone: true,
        no_exception: true,
        cred_profile: "prime",
        ltv_category: "high",
      },
    },
  },
  {
    // loan_tier_b: near_prime, standard LTV, good appraisal, VA loan
    payload: {
      policy_dot: dotMortgageApproval,
      input: {
        citizenship_status: "citizen",
        military_service: true,
        va_entitlement: true,
        property_rural: false,
        household_income_pct_area_median: 110,
        credit_score: 730,
        loan_amount: 420000,
        down_payment_pct: 0,
        employment_type: "w2",
        employment_months: 24,
        gross_annual_income: 95000,
        avg_net_income: 0,
        tax_returns_available: 0,
        retirement_income_documented: false,
        income_source_country: "US",
        forex_risk: "low",
        front_end_dti: 27,
        back_end_dti: 41,
        derogatory_marks: 1,
        collections: 0,
        foreclosure_last_7y: false,
        ltv: 100,
        appraisal_value: 420000,
        purchase_price: 420000,
        property_condition: "good",
        zoning: "residential",
        flood_zone: false,
        no_exception: true,
        cred_profile: "near_prime",
        ltv_category: "excellent",
      },
    },
  },
  {
    // cred_derog: foreclosure in last 7 years
    payload: {
      policy_dot: dotMortgageApproval,
      input: {
        citizenship_status: "permanent_resident",
        military_service: false,
        va_entitlement: false,
        property_rural: false,
        household_income_pct_area_median: 95,
        credit_score: 640,
        loan_amount: 310000,
        down_payment_pct: 20,
        employment_type: "w2",
        employment_months: 30,
        gross_annual_income: 80000,
        avg_net_income: 0,
        tax_returns_available: 0,
        retirement_income_documented: false,
        income_source_country: "US",
        forex_risk: "low",
        front_end_dti: 26,
        back_end_dti: 36,
        derogatory_marks: 0,
        collections: 0,
        foreclosure_last_7y: true,
        ltv: 80,
        appraisal_value: 390000,
        purchase_price: 390000,
        property_condition: "good",
        zoning: "residential",
        flood_zone: false,
        no_exception: true,
        cred_profile: "near_prime",
        ltv_category: "excellent",
      },
    },
  },
  // ─────────────────────────────────────────────
  // travel_visa_policy.dot
  // ─────────────────────────────────────────────
  {
    // reject_sanctioned: DPRK passport, no waiver
    payload: {
      policy_dot: dotTravelVisa,
      input: {
        passport_country: "KP",
        waiver_approved: false,
        prior_visa_violations: 0,
        purpose: "tourism",
        intended_stay_days: 10,
        sponsor_letter: false,
        host_company_letter: false,
        institution_acceptance_letter: false,
        financial_guarantee: false,
        onward_ticket: false,
        diplomatic_passport: false,
        un_travel_document: false,
        bank_balance_usd: 5000,
        property_ownership: false,
        employment_status: "employed",
        company_annual_revenue: 0,
        business_registration: false,
        tax_returns_submitted: false,
        scholarship_awarded: false,
        sponsor_verified: false,
        institution_guarantee: false,
        interpol_flag: false,
        criminal_record: false,
        terrorism_watch_list: false,
        offense_type: "",
        years_since_offense: 0,
        biometric_match: true,
        travel_countries_visited: 3,
        overstay_history: false,
        overstay_days_total: 0,
        schengen_visa_held: false,
        passport_validity_months: 24,
        photo_id_valid: true,
        application_signed: true,
        biometrics_submitted: true,
        interview_passed: true,
        police_clearance: true,
        accreditation_verified: false,
        hist_profile: "good",
        fin_profile: "strong",
        nat_category: "sanctioned",
        visa_category: "tourist",
        visa_waiver_program_list: ["DE"],
        high_risk_country_list: ["AF"],
      },
    },
  },
  {
    // visa_multiple_5yr: visa_waiver_list country, tourism, strong finances, excellent history, full docs
    payload: {
      policy_dot: dotTravelVisa,
      input: {
        passport_country: "DE",
        waiver_approved: false,
        prior_visa_violations: 0,
        purpose: "tourism",
        intended_stay_days: 30,
        sponsor_letter: true,
        host_company_letter: false,
        institution_acceptance_letter: false,
        financial_guarantee: false,
        onward_ticket: true,
        diplomatic_passport: false,
        un_travel_document: false,
        bank_balance_usd: 12000,
        property_ownership: true,
        employment_status: "employed",
        company_annual_revenue: 0,
        business_registration: false,
        tax_returns_submitted: false,
        scholarship_awarded: false,
        sponsor_verified: false,
        institution_guarantee: false,
        interpol_flag: false,
        criminal_record: false,
        terrorism_watch_list: false,
        offense_type: "",
        years_since_offense: 0,
        biometric_match: true,
        travel_countries_visited: 15,
        overstay_history: false,
        overstay_days_total: 0,
        schengen_visa_held: true,
        passport_validity_months: 36,
        photo_id_valid: true,
        application_signed: true,
        biometrics_submitted: true,
        interview_passed: true,
        police_clearance: true,
        accreditation_verified: false,
        hist_profile: "excellent",
        fin_profile: "strong",
        nat_category: "visa_free",
        visa_category: "tourist",
        visa_waiver_program_list: ["DE"],
        high_risk_country_list: ["AF"],
      },
    },
  },
  {
    // reject_invalid_category: high_risk nation, purpose=study, no acceptance letter
    payload: {
      policy_dot: dotTravelVisa,
      input: {
        passport_country: "AF",
        waiver_approved: false,
        prior_visa_violations: 0,
        purpose: "study",
        intended_stay_days: 365,
        sponsor_letter: false,
        host_company_letter: false,
        institution_acceptance_letter: false,
        financial_guarantee: false,
        onward_ticket: false,
        diplomatic_passport: false,
        un_travel_document: false,
        bank_balance_usd: 3000,
        property_ownership: false,
        employment_status: "unemployed",
        company_annual_revenue: 0,
        business_registration: false,
        tax_returns_submitted: false,
        scholarship_awarded: false,
        sponsor_verified: false,
        institution_guarantee: false,
        interpol_flag: false,
        criminal_record: false,
        terrorism_watch_list: false,
        offense_type: "",
        years_since_offense: 0,
        biometric_match: true,
        travel_countries_visited: 0,
        overstay_history: false,
        overstay_days_total: 0,
        schengen_visa_held: false,
        passport_validity_months: 12,
        photo_id_valid: true,
        application_signed: true,
        biometrics_submitted: true,
        interview_passed: false,
        police_clearance: false,
        accreditation_verified: false,
        hist_profile: "good",
        fin_profile: "weak",
        nat_category: "high_risk",
        visa_category: "student",
        visa_waiver_program_list: ["DE"],
        high_risk_country_list: ["AF"],
      },
    },
  },
  {
    // sec_reject: terrorism watch list flagged
    payload: {
      policy_dot: dotTravelVisa,
      input: {
        passport_country: "PK",
        waiver_approved: false,
        prior_visa_violations: 0,
        purpose: "tourism",
        intended_stay_days: 14,
        sponsor_letter: true,
        host_company_letter: false,
        institution_acceptance_letter: false,
        financial_guarantee: false,
        onward_ticket: true,
        diplomatic_passport: false,
        un_travel_document: false,
        bank_balance_usd: 8000,
        property_ownership: true,
        employment_status: "employed",
        company_annual_revenue: 0,
        business_registration: false,
        tax_returns_submitted: false,
        scholarship_awarded: false,
        sponsor_verified: false,
        institution_guarantee: false,
        interpol_flag: false,
        criminal_record: false,
        terrorism_watch_list: true,
        offense_type: "",
        years_since_offense: 0,
        biometric_match: true,
        travel_countries_visited: 5,
        overstay_history: false,
        overstay_days_total: 0,
        schengen_visa_held: false,
        passport_validity_months: 18,
        photo_id_valid: true,
        application_signed: true,
        biometrics_submitted: true,
        interview_passed: true,
        police_clearance: true,
        accreditation_verified: false,
        hist_profile: "good",
        fin_profile: "strong",
        nat_category: "visa_required",
        visa_category: "tourist",
        visa_waiver_program_list: ["DE"],
        high_risk_country_list: ["AF"],
      },
    },
  },
  {
    // visa_single_3m: hist=good, fin=adequate, doc_partial
    payload: {
      policy_dot: dotTravelVisa,
      input: {
        passport_country: "IN",
        waiver_approved: false,
        prior_visa_violations: 0,
        purpose: "business",
        intended_stay_days: 60,
        sponsor_letter: false,
        host_company_letter: true,
        institution_acceptance_letter: false,
        financial_guarantee: false,
        onward_ticket: true,
        diplomatic_passport: false,
        un_travel_document: false,
        bank_balance_usd: 50000,
        property_ownership: false,
        employment_status: "employed",
        company_annual_revenue: 60000,
        business_registration: true,
        tax_returns_submitted: false,
        scholarship_awarded: false,
        sponsor_verified: false,
        institution_guarantee: false,
        interpol_flag: false,
        criminal_record: false,
        terrorism_watch_list: false,
        offense_type: "",
        years_since_offense: 0,
        biometric_match: true,
        travel_countries_visited: 4,
        overstay_history: false,
        overstay_days_total: 0,
        schengen_visa_held: false,
        passport_validity_months: 4,
        photo_id_valid: true,
        application_signed: true,
        biometrics_submitted: true,
        interview_passed: true,
        police_clearance: false,
        accreditation_verified: false,
        hist_profile: "good",
        fin_profile: "adequate",
        nat_category: "visa_required",
        visa_category: "business",
        visa_waiver_program_list: ["DE"],
        high_risk_country_list: ["AF"],
      },
    },
  },
  {
    // fin_reject: tourist, bank < 500, no sponsor, unemployed
    payload: {
      policy_dot: dotTravelVisa,
      input: {
        passport_country: "NG",
        waiver_approved: false,
        prior_visa_violations: 0,
        purpose: "tourism",
        intended_stay_days: 30,
        sponsor_letter: false,
        host_company_letter: false,
        institution_acceptance_letter: false,
        financial_guarantee: false,
        onward_ticket: false,
        diplomatic_passport: false,
        un_travel_document: false,
        bank_balance_usd: 200,
        property_ownership: false,
        employment_status: "unemployed",
        company_annual_revenue: 0,
        business_registration: false,
        tax_returns_submitted: false,
        scholarship_awarded: false,
        sponsor_verified: false,
        institution_guarantee: false,
        interpol_flag: false,
        criminal_record: false,
        terrorism_watch_list: false,
        offense_type: "",
        years_since_offense: 0,
        biometric_match: true,
        travel_countries_visited: 1,
        overstay_history: false,
        overstay_days_total: 0,
        schengen_visa_held: false,
        passport_validity_months: 20,
        photo_id_valid: true,
        application_signed: true,
        biometrics_submitted: true,
        interview_passed: true,
        police_clearance: true,
        accreditation_verified: false,
        hist_profile: "good",
        fin_profile: "weak",
        nat_category: "visa_required",
        visa_category: "tourist",
        visa_waiver_program_list: ["DE"],
        high_risk_country_list: ["AF"],
      },
    },
  },
  // ─────────────────────────────────────────────
  // employee_hiring_policy.dot
  // ─────────────────────────────────────────────
  {
    // reject_headcount_freeze: freeze active, no exception
    payload: {
      policy_dot: dotEmployeeHiring,
      input: {
        headcount_freeze: true,
        exception_approved: false,
        requisition_approved: true,
        employment_type: "full_time",
        seniority_band: 3,
        contract_vendor_approved: false,
        resume_submitted: true,
        cover_letter: true,
        work_authorization: true,
        age: 28,
        portfolio_or_samples: true,
        years_experience: 5,
        references_provided: 2,
        board_intro_complete: false,
        gross_annual_income: 0,
        vendor_contract_signed: false,
        technical_score: 80,
        domain_expertise_match: 75,
        certifications_required: 0,
        certifications_held: 0,
        behavioral_score: 85,
        collaboration_rating: 80,
        values_alignment_score: 78,
        criminal_record: false,
        offense_type: "",
        years_since_offense: 0,
        employment_gaps_explained: true,
        reference_check_passed: true,
        education_verified: true,
        no_prior_terminations: true,
        education_falsified: false,
        candidate_salary_expectation: 90000,
        role_salary_min: 80000,
        role_salary_max: 110000,
        exceptional_talent_flag: false,
        vp_override: false,
        vp_approval: false,
        ceo_approval: false,
        culture_profile: "good",
        skills_profile: "strong",
      },
    },
  },
  {
    // hire_fast_track: senior band, strong skills, excellent culture, bg_clear, within band, CEO approved
    payload: {
      policy_dot: dotEmployeeHiring,
      input: {
        headcount_freeze: false,
        exception_approved: false,
        requisition_approved: true,
        employment_type: "full_time",
        seniority_band: 7,
        contract_vendor_approved: false,
        resume_submitted: true,
        cover_letter: true,
        work_authorization: true,
        age: 38,
        portfolio_or_samples: true,
        years_experience: 12,
        references_provided: 3,
        board_intro_complete: false,
        gross_annual_income: 0,
        vendor_contract_signed: false,
        technical_score: 92,
        domain_expertise_match: 88,
        certifications_required: 1,
        certifications_held: 2,
        behavioral_score: 93,
        collaboration_rating: 90,
        values_alignment_score: 88,
        criminal_record: false,
        offense_type: "",
        years_since_offense: 0,
        employment_gaps_explained: true,
        reference_check_passed: true,
        education_verified: true,
        no_prior_terminations: true,
        education_falsified: false,
        candidate_salary_expectation: 160000,
        role_salary_min: 140000,
        role_salary_max: 170000,
        exceptional_talent_flag: true,
        vp_override: false,
        vp_approval: true,
        ceo_approval: true,
        culture_profile: "excellent",
        skills_profile: "strong",
      },
    },
  },
  {
    // reject_req_not_approved: requisition not approved, no freeze
    payload: {
      policy_dot: dotEmployeeHiring,
      input: {
        headcount_freeze: false,
        exception_approved: false,
        requisition_approved: false,
        employment_type: "full_time",
        seniority_band: 4,
        contract_vendor_approved: false,
        resume_submitted: true,
        cover_letter: false,
        work_authorization: true,
        age: 30,
        portfolio_or_samples: false,
        years_experience: 6,
        references_provided: 1,
        board_intro_complete: false,
        gross_annual_income: 0,
        vendor_contract_signed: false,
        technical_score: 75,
        domain_expertise_match: 70,
        certifications_required: 0,
        certifications_held: 0,
        behavioral_score: 78,
        collaboration_rating: 72,
        values_alignment_score: 70,
        criminal_record: false,
        offense_type: "",
        years_since_offense: 0,
        employment_gaps_explained: true,
        reference_check_passed: true,
        education_verified: true,
        no_prior_terminations: true,
        education_falsified: false,
        candidate_salary_expectation: 100000,
        role_salary_min: 90000,
        role_salary_max: 120000,
        exceptional_talent_flag: false,
        vp_override: false,
        vp_approval: false,
        ceo_approval: false,
        culture_profile: "good",
        skills_profile: "adequate",
      },
    },
  },
  {
    // skills_disqualify: technical_score < 50
    payload: {
      policy_dot: dotEmployeeHiring,
      input: {
        headcount_freeze: false,
        exception_approved: false,
        requisition_approved: true,
        employment_type: "full_time",
        seniority_band: 3,
        contract_vendor_approved: false,
        resume_submitted: true,
        cover_letter: true,
        work_authorization: true,
        age: 25,
        portfolio_or_samples: false,
        years_experience: 4,
        references_provided: 1,
        board_intro_complete: false,
        gross_annual_income: 0,
        vendor_contract_signed: false,
        technical_score: 42,
        domain_expertise_match: 38,
        certifications_required: 0,
        certifications_held: 0,
        behavioral_score: 80,
        collaboration_rating: 75,
        values_alignment_score: 72,
        criminal_record: false,
        offense_type: "",
        years_since_offense: 0,
        employment_gaps_explained: true,
        reference_check_passed: true,
        education_verified: true,
        no_prior_terminations: true,
        education_falsified: false,
        candidate_salary_expectation: 75000,
        role_salary_min: 70000,
        role_salary_max: 95000,
        exceptional_talent_flag: false,
        vp_override: false,
        vp_approval: false,
        ceo_approval: false,
        culture_profile: "good",
        skills_profile: "weak",
      },
    },
  },
  {
    // bg_disqualify: felony criminal record
    payload: {
      policy_dot: dotEmployeeHiring,
      input: {
        headcount_freeze: false,
        exception_approved: false,
        requisition_approved: true,
        employment_type: "full_time",
        seniority_band: 4,
        contract_vendor_approved: false,
        resume_submitted: true,
        cover_letter: true,
        work_authorization: true,
        age: 34,
        portfolio_or_samples: true,
        years_experience: 8,
        references_provided: 2,
        board_intro_complete: false,
        gross_annual_income: 0,
        vendor_contract_signed: false,
        technical_score: 82,
        domain_expertise_match: 78,
        certifications_required: 1,
        certifications_held: 1,
        behavioral_score: 85,
        collaboration_rating: 82,
        values_alignment_score: 80,
        criminal_record: true,
        offense_type: "felony",
        years_since_offense: 3,
        employment_gaps_explained: true,
        reference_check_passed: true,
        education_verified: true,
        no_prior_terminations: true,
        education_falsified: false,
        candidate_salary_expectation: 115000,
        role_salary_min: 100000,
        role_salary_max: 130000,
        exceptional_talent_flag: false,
        vp_override: false,
        vp_approval: false,
        ceo_approval: false,
        culture_profile: "good",
        skills_profile: "strong",
      },
    },
  },
  {
    // hire_contractor: contractor employment type, vendor approved
    payload: {
      policy_dot: dotEmployeeHiring,
      input: {
        headcount_freeze: false,
        exception_approved: false,
        requisition_approved: true,
        employment_type: "contractor",
        seniority_band: 4,
        contract_vendor_approved: true,
        resume_submitted: true,
        cover_letter: false,
        work_authorization: true,
        age: 32,
        portfolio_or_samples: true,
        years_experience: 7,
        references_provided: 1,
        board_intro_complete: false,
        gross_annual_income: 0,
        vendor_contract_signed: true,
        technical_score: 80,
        domain_expertise_match: 76,
        certifications_required: 0,
        certifications_held: 0,
        behavioral_score: 82,
        collaboration_rating: 78,
        values_alignment_score: 76,
        criminal_record: false,
        offense_type: "",
        years_since_offense: 0,
        employment_gaps_explained: true,
        reference_check_passed: true,
        education_verified: true,
        no_prior_terminations: true,
        education_falsified: false,
        candidate_salary_expectation: 120000,
        role_salary_min: 100000,
        role_salary_max: 140000,
        exceptional_talent_flag: false,
        vp_override: false,
        vp_approval: false,
        ceo_approval: false,
        culture_profile: "good",
        skills_profile: "adequate",
      },
    },
  },
  {
    // offer_reject_comp: comp expectation > max * 1.15, no exceptional flag
    payload: {
      policy_dot: dotEmployeeHiring,
      input: {
        headcount_freeze: false,
        exception_approved: false,
        requisition_approved: true,
        employment_type: "full_time",
        seniority_band: 5,
        contract_vendor_approved: false,
        resume_submitted: true,
        cover_letter: true,
        work_authorization: true,
        age: 35,
        portfolio_or_samples: true,
        years_experience: 9,
        references_provided: 2,
        board_intro_complete: false,
        gross_annual_income: 0,
        vendor_contract_signed: false,
        technical_score: 88,
        domain_expertise_match: 85,
        certifications_required: 0,
        certifications_held: 1,
        behavioral_score: 88,
        collaboration_rating: 85,
        values_alignment_score: 83,
        criminal_record: false,
        offense_type: "",
        years_since_offense: 0,
        employment_gaps_explained: true,
        reference_check_passed: true,
        education_verified: true,
        no_prior_terminations: true,
        education_falsified: false,
        candidate_salary_expectation: 200000,
        role_salary_min: 110000,
        role_salary_max: 140000,
        exceptional_talent_flag: false,
        vp_override: false,
        vp_approval: false,
        ceo_approval: false,
        culture_profile: "excellent",
        skills_profile: "strong",
      },
    },
  },
  // ─────────────────────────────────────────────
  // medical_claims_adjudication.dot
  // ─────────────────────────────────────────────
  {
    // reject_duplicate: duplicate claim, no override
    payload: {
      policy_dot: dotMedicalClaims,
      input: {
        duplicate_claim_detected: true,
        override_duplicate: false,
        days_since_service: 30,
        timely_filing_exception: false,
        exception_reason: "",
        claim_form_complete: true,
        corrected_claim_submitted: false,
        electronic_submission: true,
        member_active_on_dos: true,
        coverage_type: "employer",
        premium_paid_thru: "2026-01-31",
        date_of_service: "2026-01-15",
        cobra_premium_paid: false,
        retroactive_enrollment_approved: false,
        retro_effective_date: "",
        grace_period_days: 30,
        provider_licensed: true,
        provider_sanctioned: false,
        provider_network_status: "in_network",
        claim_type: "routine",
        service_requires_auth: false,
        prior_auth_status: "not_required",
        auth_service_matches_claim: true,
        experimental_treatment: false,
        clinical_trial_approved: false,
        emergency_verified: false,
        out_of_network_exception: false,
        other_insurance: false,
        annual_benefit_used: 1000,
        annual_benefit_max: 10000,
        lifetime_max_reached: false,
        primary_paid_amount: 0,
        allowed_amount: 300,
        auto_adjudicate_pending: false,
        ytd_member_oop: 500,
        oop_max_individual: 5000,
        deductible_met: true,
        copay_amount: 20,
        coinsurance_pct: 0,
        fraud_score: 5,
        claim_amount: 300,
        expected_allowed_amount: 300,
        provider_fraud_flag: false,
        fee_schedule_variance: 0.02,
        clinical_edit_failure: false,
        no_edit_failures: true,
      },
    },
  },
  {
    // pay_clean: valid, eligible, in-network, no auth required, primary, oop not met, low fraud, clean edits
    payload: {
      policy_dot: dotMedicalClaims,
      input: {
        duplicate_claim_detected: false,
        override_duplicate: false,
        days_since_service: 45,
        timely_filing_exception: false,
        exception_reason: "",
        claim_form_complete: true,
        corrected_claim_submitted: false,
        electronic_submission: true,
        member_active_on_dos: true,
        coverage_type: "employer",
        premium_paid_thru: "2026-03-31",
        date_of_service: "2026-01-20",
        cobra_premium_paid: false,
        retroactive_enrollment_approved: false,
        retro_effective_date: "",
        grace_period_days: 30,
        provider_licensed: true,
        provider_sanctioned: false,
        provider_network_status: "in_network",
        claim_type: "routine",
        service_requires_auth: false,
        prior_auth_status: "not_required",
        auth_service_matches_claim: true,
        experimental_treatment: false,
        clinical_trial_approved: false,
        emergency_verified: false,
        out_of_network_exception: false,
        other_insurance: false,
        annual_benefit_used: 2000,
        annual_benefit_max: 15000,
        lifetime_max_reached: false,
        primary_paid_amount: 0,
        allowed_amount: 450,
        auto_adjudicate_pending: false,
        ytd_member_oop: 1000,
        oop_max_individual: 6000,
        deductible_met: true,
        copay_amount: 30,
        coinsurance_pct: 0,
        fraud_score: 8,
        claim_amount: 450,
        expected_allowed_amount: 450,
        provider_fraud_flag: false,
        fee_schedule_variance: 0.01,
        clinical_edit_failure: false,
        no_edit_failures: true,
      },
    },
  },
  {
    // reject_late_filing: days_since_service > 365, no exception
    payload: {
      policy_dot: dotMedicalClaims,
      input: {
        duplicate_claim_detected: false,
        override_duplicate: false,
        days_since_service: 400,
        timely_filing_exception: false,
        exception_reason: "",
        claim_form_complete: true,
        corrected_claim_submitted: false,
        electronic_submission: false,
        member_active_on_dos: true,
        coverage_type: "employer",
        premium_paid_thru: "2026-03-31",
        date_of_service: "2025-01-01",
        cobra_premium_paid: false,
        retroactive_enrollment_approved: false,
        retro_effective_date: "",
        grace_period_days: 30,
        provider_licensed: true,
        provider_sanctioned: false,
        provider_network_status: "in_network",
        claim_type: "routine",
        service_requires_auth: false,
        prior_auth_status: "not_required",
        auth_service_matches_claim: true,
        experimental_treatment: false,
        clinical_trial_approved: false,
        emergency_verified: false,
        out_of_network_exception: false,
        other_insurance: false,
        annual_benefit_used: 500,
        annual_benefit_max: 10000,
        lifetime_max_reached: false,
        primary_paid_amount: 0,
        allowed_amount: 200,
        auto_adjudicate_pending: false,
        ytd_member_oop: 200,
        oop_max_individual: 5000,
        deductible_met: false,
        copay_amount: 0,
        coinsurance_pct: 20,
        fraud_score: 5,
        claim_amount: 200,
        expected_allowed_amount: 200,
        provider_fraud_flag: false,
        fee_schedule_variance: 0.0,
        clinical_edit_failure: false,
        no_edit_failures: true,
      },
    },
  },
  {
    // elig_terminated: member not active on DOS, no retro enrollment
    payload: {
      policy_dot: dotMedicalClaims,
      input: {
        duplicate_claim_detected: false,
        override_duplicate: false,
        days_since_service: 20,
        timely_filing_exception: false,
        exception_reason: "",
        claim_form_complete: true,
        corrected_claim_submitted: false,
        electronic_submission: true,
        member_active_on_dos: false,
        coverage_type: "employer",
        premium_paid_thru: "2025-12-31",
        date_of_service: "2026-01-10",
        cobra_premium_paid: false,
        retroactive_enrollment_approved: false,
        retro_effective_date: "",
        grace_period_days: 0,
        provider_licensed: true,
        provider_sanctioned: false,
        provider_network_status: "in_network",
        claim_type: "routine",
        service_requires_auth: false,
        prior_auth_status: "not_required",
        auth_service_matches_claim: true,
        experimental_treatment: false,
        clinical_trial_approved: false,
        emergency_verified: false,
        out_of_network_exception: false,
        other_insurance: false,
        annual_benefit_used: 0,
        annual_benefit_max: 10000,
        lifetime_max_reached: false,
        primary_paid_amount: 0,
        allowed_amount: 150,
        auto_adjudicate_pending: false,
        ytd_member_oop: 0,
        oop_max_individual: 5000,
        deductible_met: false,
        copay_amount: 20,
        coinsurance_pct: 0,
        fraud_score: 3,
        claim_amount: 150,
        expected_allowed_amount: 150,
        provider_fraud_flag: false,
        fee_schedule_variance: 0.0,
        clinical_edit_failure: false,
        no_edit_failures: true,
      },
    },
  },
  {
    // auth_denied: service requires auth, status=not_obtained, not an emergency
    payload: {
      policy_dot: dotMedicalClaims,
      input: {
        duplicate_claim_detected: false,
        override_duplicate: false,
        days_since_service: 60,
        timely_filing_exception: false,
        exception_reason: "",
        claim_form_complete: true,
        corrected_claim_submitted: false,
        electronic_submission: true,
        member_active_on_dos: true,
        coverage_type: "employer",
        premium_paid_thru: "2026-06-30",
        date_of_service: "2025-12-25",
        cobra_premium_paid: false,
        retroactive_enrollment_approved: false,
        retro_effective_date: "",
        grace_period_days: 30,
        provider_licensed: true,
        provider_sanctioned: false,
        provider_network_status: "in_network",
        claim_type: "elective_surgery",
        service_requires_auth: true,
        prior_auth_status: "not_obtained",
        auth_service_matches_claim: false,
        experimental_treatment: false,
        clinical_trial_approved: false,
        emergency_verified: false,
        out_of_network_exception: false,
        other_insurance: false,
        annual_benefit_used: 3000,
        annual_benefit_max: 12000,
        lifetime_max_reached: false,
        primary_paid_amount: 0,
        allowed_amount: 8000,
        auto_adjudicate_pending: false,
        ytd_member_oop: 2000,
        oop_max_individual: 7000,
        deductible_met: true,
        copay_amount: 0,
        coinsurance_pct: 20,
        fraud_score: 10,
        claim_amount: 8000,
        expected_allowed_amount: 8000,
        provider_fraud_flag: false,
        fee_schedule_variance: 0.0,
        clinical_edit_failure: false,
        no_edit_failures: true,
      },
    },
  },
  {
    // cost_share_max_oop: OOP max already met → member liability 0
    payload: {
      policy_dot: dotMedicalClaims,
      input: {
        duplicate_claim_detected: false,
        override_duplicate: false,
        days_since_service: 10,
        timely_filing_exception: false,
        exception_reason: "",
        claim_form_complete: true,
        corrected_claim_submitted: false,
        electronic_submission: true,
        member_active_on_dos: true,
        coverage_type: "employer",
        premium_paid_thru: "2026-12-31",
        date_of_service: "2026-02-01",
        cobra_premium_paid: false,
        retroactive_enrollment_approved: false,
        retro_effective_date: "",
        grace_period_days: 30,
        provider_licensed: true,
        provider_sanctioned: false,
        provider_network_status: "in_network",
        claim_type: "routine",
        service_requires_auth: false,
        prior_auth_status: "not_required",
        auth_service_matches_claim: true,
        experimental_treatment: false,
        clinical_trial_approved: false,
        emergency_verified: false,
        out_of_network_exception: false,
        other_insurance: false,
        annual_benefit_used: 5000,
        annual_benefit_max: 15000,
        lifetime_max_reached: false,
        primary_paid_amount: 0,
        allowed_amount: 300,
        auto_adjudicate_pending: false,
        ytd_member_oop: 6000,
        oop_max_individual: 6000,
        deductible_met: true,
        copay_amount: 0,
        coinsurance_pct: 0,
        fraud_score: 4,
        claim_amount: 300,
        expected_allowed_amount: 300,
        provider_fraud_flag: false,
        fee_schedule_variance: 0.0,
        clinical_edit_failure: false,
        no_edit_failures: true,
      },
    },
  },
  {
    // fraud_high_review: provider_fraud_flag=true
    payload: {
      policy_dot: dotMedicalClaims,
      input: {
        duplicate_claim_detected: false,
        override_duplicate: false,
        days_since_service: 30,
        timely_filing_exception: false,
        exception_reason: "",
        claim_form_complete: true,
        corrected_claim_submitted: false,
        electronic_submission: true,
        member_active_on_dos: true,
        coverage_type: "employer",
        premium_paid_thru: "2026-06-30",
        date_of_service: "2026-01-25",
        cobra_premium_paid: false,
        retroactive_enrollment_approved: false,
        retro_effective_date: "",
        grace_period_days: 30,
        provider_licensed: true,
        provider_sanctioned: false,
        provider_network_status: "in_network",
        claim_type: "routine",
        service_requires_auth: false,
        prior_auth_status: "not_required",
        auth_service_matches_claim: true,
        experimental_treatment: false,
        clinical_trial_approved: false,
        emergency_verified: false,
        out_of_network_exception: false,
        other_insurance: false,
        annual_benefit_used: 1500,
        annual_benefit_max: 10000,
        lifetime_max_reached: false,
        primary_paid_amount: 0,
        allowed_amount: 500,
        auto_adjudicate_pending: false,
        ytd_member_oop: 800,
        oop_max_individual: 5000,
        deductible_met: true,
        copay_amount: 20,
        coinsurance_pct: 0,
        fraud_score: 22,
        claim_amount: 1200,
        expected_allowed_amount: 500,
        provider_fraud_flag: true,
        fee_schedule_variance: 0.0,
        clinical_edit_failure: false,
        no_edit_failures: true,
      },
    },
  },
  {
    // pay_adjusted: low fraud but fee_schedule_variance > 5% and <= 20%
    payload: {
      policy_dot: dotMedicalClaims,
      input: {
        duplicate_claim_detected: false,
        override_duplicate: false,
        days_since_service: 15,
        timely_filing_exception: false,
        exception_reason: "",
        claim_form_complete: true,
        corrected_claim_submitted: false,
        electronic_submission: true,
        member_active_on_dos: true,
        coverage_type: "employer",
        premium_paid_thru: "2026-12-31",
        date_of_service: "2026-02-10",
        cobra_premium_paid: false,
        retroactive_enrollment_approved: false,
        retro_effective_date: "",
        grace_period_days: 30,
        provider_licensed: true,
        provider_sanctioned: false,
        provider_network_status: "in_network",
        claim_type: "routine",
        service_requires_auth: false,
        prior_auth_status: "not_required",
        auth_service_matches_claim: true,
        experimental_treatment: false,
        clinical_trial_approved: false,
        emergency_verified: false,
        out_of_network_exception: false,
        other_insurance: false,
        annual_benefit_used: 800,
        annual_benefit_max: 10000,
        lifetime_max_reached: false,
        primary_paid_amount: 0,
        allowed_amount: 600,
        auto_adjudicate_pending: false,
        ytd_member_oop: 400,
        oop_max_individual: 5000,
        deductible_met: true,
        copay_amount: 0,
        coinsurance_pct: 10,
        fraud_score: 12,
        claim_amount: 700,
        expected_allowed_amount: 600,
        provider_fraud_flag: false,
        fee_schedule_variance: 0.12,
        clinical_edit_failure: false,
        no_edit_failures: true,
      },
    },
  },
  {
    // prov_unlicensed_reject: provider not licensed
    payload: {
      policy_dot: dotMedicalClaims,
      input: {
        duplicate_claim_detected: false,
        override_duplicate: false,
        days_since_service: 20,
        timely_filing_exception: false,
        exception_reason: "",
        claim_form_complete: true,
        corrected_claim_submitted: false,
        electronic_submission: true,
        member_active_on_dos: true,
        coverage_type: "employer",
        premium_paid_thru: "2026-12-31",
        date_of_service: "2026-02-05",
        cobra_premium_paid: false,
        retroactive_enrollment_approved: false,
        retro_effective_date: "",
        grace_period_days: 30,
        provider_licensed: false,
        provider_sanctioned: false,
        provider_network_status: "in_network",
        claim_type: "routine",
        service_requires_auth: false,
        prior_auth_status: "not_required",
        auth_service_matches_claim: true,
        experimental_treatment: false,
        clinical_trial_approved: false,
        emergency_verified: false,
        out_of_network_exception: false,
        other_insurance: false,
        annual_benefit_used: 500,
        annual_benefit_max: 10000,
        lifetime_max_reached: false,
        primary_paid_amount: 0,
        allowed_amount: 250,
        auto_adjudicate_pending: false,
        ytd_member_oop: 300,
        oop_max_individual: 5000,
        deductible_met: false,
        copay_amount: 25,
        coinsurance_pct: 0,
        fraud_score: 5,
        claim_amount: 250,
        expected_allowed_amount: 250,
        provider_fraud_flag: false,
        fee_schedule_variance: 0.0,
        clinical_edit_failure: false,
        no_edit_failures: true,
      },
    },
  },
];
